### ISSUE TITLE
Markdown example

### ISSUE THREAD

**Issue by nokome** [stencila/examples#6]
We need a "self-documenting" , instructional example called `markdown` for Markdown that describes how to use that format with Stencila. See some of the other examples in the series:

- https://github.com/stencila/examples/tree/master/rmarkdown
- https://github.com/stencila/examples/tree/master/jupyter

We already have a nacent Markdown example on HackMD: https://hackmd.io/RaFYCFoyTlODFxz5hPevLw. For the sake of having all the examples in this repo (at least linked to), I suggest that we use the HacKMD Github integration to push / pull to the `markdown` directory in this repo.

**Comment by alex-ketch** [comment]
I like the HackMD idea, but doesn't look like I have the permissions to set up the integration.
Could I ask you to do that please @nokome?

**Comment by alex-ketch** [comment]
The HackMD document linked above should be ready for review, as mentioned though the GitHub sync has to be done by you I think @nokome
